knative-extensions/.github

- workflow-templates/stale.properties.json
> Drop trailing comma

- workflow-templates/knative-style.yaml
Has been tested and reviewed over here: https://github.com/knative/serving/pull/9327/
> Add an action that warns about usages of divisive language.

- workflow-templates/knative-go-build.yaml
This will now report build failures for all test code
> use vet with tags - it will report build failures

- workflow-templates/knative-go-build.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-stale.yaml
- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
As per title, I don't think anybody pays attention to these, so let's not run them.
> Don't run actions on push, nobody checks those.

- workflow-templates/knative-style.yaml
As per title. It breaks in postsubmits.
> Run woke checks only on PRs.

- workflow-templates/knative-go-build.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
if you include a .codecov.yaml file in the root of the repo. For example:
```yaml
ignore:
- "**/zz_generated*.go" # Ignore generated files.
- "pkg/client"
- "third_party"
- "vendor"
```
> Enable codecov

- workflow-templates/knative-donotsubmit.properties.json
- workflow-templates/knative-donotsubmit.yaml
This runs a very simple action that replaces my "DO NOT SUBMIT" bot using grep and reviewdog.
It excludes files within `vendor` and `third_party`, as well as itself.
You can see a run of this in action here: https://github.com/knative/serving/pull/9467
> Add a DO NOT SUBMIT action.

- workflow-templates/knative-donotsubmit.yaml
- workflow-templates/knative-style.yaml
1. Don't fail due to grep/misspell errors, let reviewdog establish failure.
2. Run `gofmt` last since it alters the workspace
3. Run style steps even if prior steps failed
/assign @n3wscott @markusthoemmes @tcnghia @dprotaso
> Several workflow adjustments

- workflow-templates/knative-style.yaml
You can see the results here: https://github.com/knative/serving/pull/9478/commits/8e61a2a32b88b84cc4b4002ca3ae68ef0b83773b
/assign @n3wscott
> Add a check for trailing whitespace.

- workflow-templates/knative-style.yaml
See this in action here: https://github.com/knative/serving/pull/9481
> Add a step to flag missing newlines at EOF.

- workflow-templates/knative-style.yaml
Also exclude generated proto files.
> Add goimports checking

- workflow-templates/knative-style.yaml
Fixes: https://github.com/knative-sandbox/.github/issues/27
> Combine installations of reviewdog.

- workflow-templates/knative-go-build.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
The race should be fixed already.
Fixes #26
> Try again go 1.15

- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
You can see this in action here: https://github.com/knative/serving/pull/9583/files
/assign @markusthoemmes @vagababov
> Turn the output of auto formatting tools into error annotations.

- workflow-templates/knative-style.yaml
> Cover the rare case of %T

- workflow-templates/knative-style.yaml
> Capture t.Logf in addition

- workflow-templates/knative-style.yaml
- avoid %x, since it's a specific format
- add Fprintf, Printf and Sprintf, duh.
/assign mattmoor
> Cover some edgecases I found while updating other repos

- workflow-templates/knative-boilerplate.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-style.yaml
fixes: https://github.com/knative-sandbox/.github/issues/50
tested on: https://github.com/knative-sandbox/discovery/pull/86
> do not use set-env or add-path

- workflow-templates/knative-style.yaml
tested: https://github.com/knative/docs/pull/2893
> do not lint .ai files.

- workflow-templates/knative-security.yaml
Results in failures in actions sync
> Fix knative-security whitespace lint

- workflow-templates/knative-style.yaml
As per title. This apparently got dropped in refactors.
> Pin woke version again to avoid breaks from sneaking in

- workflow-templates/knative-releasability.properties.json
- workflow-templates/knative-releasability.yaml
I am not sure what happened, I added this a while ago and it was removed? But it looks like a mistake on github side: https://github.com/knative-sandbox/.github/pull/59
> adding releasability action

- workflow-templates/knative-style.yaml
> Bump golangci-lint version

- workflow-templates/knative-style.yaml
> Show (-got,+want) stuff in the formatter

- workflow-templates/knative-release-notes.properties.json
- workflow-templates/knative-release-notes.yaml
see https://github.com/n3wscott/eventing/runs/1343788652?check_suite_focus=true for an example run.
> to support releases, adding a manual only release notes generator workflow

- workflow-templates/knative-style.yaml
This was just printing the original line.
Here's a fix in motion: https://github.com/knative/serving/pull/10046/files#diff-1f0a6c58f9e37bedb9beb203fcc86e94934ef325969eca6f8713cd74222080f8R85
/assign mattmoor
> Fix a bug in t.Xf() reporting

- workflow-templates/knative-releasability.yaml
> Skip slack notification when SLACK_WEBHOOK not set.

- workflow-templates/knative-verify.yaml
- :bug: Use ko v0.6.0 to avoid installation problem
/kind bug
/area test-and-release
Fixes #
```release-note
NONE
```
**Docs**
```docs
NONE
```
> Use ko v0.6.0

- workflow-templates/knative-releasability.yaml
- :bug: Fixing an issue where we are not allowed to test github secrets in the if blocks of steps. 
/kind bug
Fixes https://github.com/knative-sandbox/.github/issues/84
> add a flag to test if webhook secrets are set.

- .github/CODEOWNERS
> Put all owners into a single line

- workflow-templates/knative-style.yaml
[a very very silly person](http://github.com/julz) named a linter [`importas`](http://github.com/julz/importas) so now we need to do this 😢 
/assign @markusthoemmes
> Ignore spurious misspell complaint

- workflow-templates/knative-releasability.yaml
As per the release docs https://github.com/knative/release#update-the-knative-releasability-defaults.
/assign @evankanderson
> Bump releasability action to start asserting v0.22

- workflow-templates/knative-releasability.yaml
Update the release to 0.23 as per https://github.com/knative/release
/assign @tcnghia
> bump release to 0.23

- workflow-templates/knative-releasability.yaml
- :broom: :bug: Knobots auto-upgrades ignores `go.mod` for the nightly runs. This code was copied into the `releasability` workflow, but we want the release branches to be pinned to the actual upstream release.
/kind bug
/kind cleanup
**Docs**
> Don't ignore go.mod for releasability

- workflow-templates/knative-boilerplate.yaml
- workflow-templates/knative-go-build.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-releasability.yaml
- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
- :broom: Bump Go to 1.16
As @n3wscott mentioned in the TOC on 4/22 we're going to bump all of Knative to 1.16. I think there's a bunch of steps distributed all over the place, but this is the start?!
> Bump to go 1.16

- workflow-templates/knative-go-test.yaml
The root of the problem appears to be here:
https://github.com/knative/pkg/issues/2113
This PR basically brings in this change so that all the repos that seem to be broken get the fix.
https://github.com/knative-sandbox/eventing-kafka-broker/pull/879
> fix coverage

- workflow-templates/knative-go-test.yaml
Reverts knative-sandbox/.github#111
> Revert "fix coverage"

- workflow-templates/knative-style.yaml
Title. So we don't fall behind too much. Tested all repos and they seemed to be fine.
> Update woke to 0.8.0

- workflow-templates/knative-style.yaml
Title. So we don't fall back too much. This shouldn't contain any breaking changes.
/assign @julz
> Update golangci-lint to 1.40

- workflow-templates/knative-boilerplate.yaml
- workflow-templates/knative-donotsubmit.yaml
- workflow-templates/knative-go-build.yaml
- workflow-templates/knative-go-test.yaml
- workflow-templates/knative-security.yaml
- workflow-templates/knative-style.yaml
- workflow-templates/knative-verify.yaml
- Add `mkdocs` branch to actions that act on `main`. This should be a no-op outside of `docs`
This prevents changes like this, which have to be rejected in docs: https://github.com/knative/docs/pull/3675/files
> Add mkdocs branch to templates to support docs migration

- workflow-templates/knative-releasability.yaml
We're no longer hosting knobots at Matt's :)
/assign @n3wscott @julz
> Fix link to knobots repo

- workflow-templates/knative-vulnerability.properties.json
- workflow-templates/knative-vulnerability.yaml
As discussed [in Slack](https://knative.slack.com/archives/C01JBD1LSF3/p1622032257125300) this adds vulnerability scanning using snyk.io to all of our repositories. We'll have to configure a Snyk Token and will get 200 tests for free per month, which is why this is configured to run twice per month (we currently have 67 repositories).
See https://github.com/snyk/actions/tree/master/golang#uploading-snyk-scan-results-to-github-code-scanning for more information on the actions in use.
/hold
To finish up discussions.
> Add a snyk scanning action

- workflow-templates/knative-go-test.yaml
- :broom: Merge against upstream main branch before running any unit tests
/kind <kind>
Fixes #119
> Ensure tests are run against up to date branch

- workflow-templates/knative-releasability.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Prep for 0.26

- workflow-templates/knative-style.yaml
The usual keeping-things-clean
/assign @julz
> Update the golangci-lint version to 1.43

- workflow-templates/knative-releasability.yaml
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- as per title and doc https://github.com/knative/release#14-days-prior-to-the-release 
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Bump releasability action to start asserting v1.1

- .github/workflows/knative-security.yaml
Add a check to prevent CVE-2021-42574 and CVE-2021-42694.
See example failed check: https://github.com/pierDipi/unicode-control-characters-action-tests/pull/2/files
- Use https://github.com/pierDipi/unicode-control-characters-action action in security workflow
- Add a security workflow in this repository that uses the same action
Fixes https://github.com/knative/.github/issues/16
```release-note
Add a check to prevent CVE-2021-42574 and CVE-2021-42694
```
**Docs**
```docs
None
```
> Add a check to prevent CVE-2021-42574 and CVE-2021-42694

- .github/workflows/sync.yaml
> fix function

- workflow-templates/knative-style.yaml
ignoring all style checks for svg files, this affects docs repo
> add ignore for svg in all style checks

- .github/workflows/check-source-of-truth.yaml
- .github/workflows/sync.yaml
- README.md
This is an auotmated PR to replace  strings to . Do not merge until Rename knative-sandbox org is renamed to knative-extensions
> HoldTillRename: Rename knative-sandbox to knative-extensions

- .github/PULL_REQUEST_TEMPLATE.md
- ISSUE-TEMPLATE.md
Related https://github.com/knative/community/issues/1251
Add a default issue template and update default PR template with the adopter form information.
> Add a default issue template and update default PR template
