README.md, workflow-templates/README.md, workflow-templates/knative-go-build.yaml, workflow-templates/knative-go-test.yaml, workflow-templates/knative-stale.yaml, workflow-templates/knative-style.yaml, workflow-templates/knative-verify.yaml
Currently the workflows show up to repos (like Eventing, and it's easy enough to make manual changes), add a blurp saying where and how the files get in.
@mattmoor can you also add this to list of files to sync?
=> add a README saying these are autogen and where they come from

workflow-templates/knative-go-build.yaml, workflow-templates/knative-go-test.yaml, workflow-templates/knative-style.yaml, workflow-templates/knative-verify.yaml
Switch all GitHub actions to use Go 1.14, as we discussed in https://knative.slack.com/archives/CCSNR4FCH/p1598978184060300
=> Switch all GitHub actions to use Go 1.14

workflow-templates/knative-style.yaml
This action will only run if a golangci lint configuration is present in the respective repository for us to be able to gradually roll it out.
=> Add golangci-lint action to the code style action.

workflow-templates/knative-go-build.yaml
As per title. `golangci-lint` runs `go vet` too and allows us more control over the reported warnings.
=> Drop go vet from the actions, it's redundant with linting.

workflow-templates/knative-go-build.yaml
in this case we're fine to ignore it
=> grep returns an exit code when there are no matches 

workflow-templates/knative-style.yaml
I added these to a new repo and started seeing it firing on stuff in vendor.
I checked the `woke` repo and their `.wokeignore` file has stuff like `pkg/*`.
=> Fix default .wokeignore with *

workflow-templates/knative-donotsubmit.yaml, workflow-templates/knative-style.yaml
I found that the previous `find` commands were not recursing into `vendor`, but were returning a `./vendor` entry even though it was not a `-type f`.  I found the article below, which gave another alternative and it seems to work where the current command falls short.
The addition of `./vendor` to the list was causing `misspell` to flag spelling errors within files in `vendor/` even though they were not fully enumerated.
See: https://linuxconfig.org/how-to-explicitly-exclude-directory-from-find-command-s-search
=> Fixup the finds to properly exclude vendor et al

.github/workflows/check-source-of-truth.yaml, .github/workflows/sync.yaml, README.md
This PR does three things:
1. Update the README to describe the relationship between `knative-sandbox/.github`
and downstream `.github` repositories.
2. Add a PR check that fails when PRs are opened against downstream `.github` repositories.
3. Add a cron to mirror upstream into downstream.
Fixes: https://github.com/knative-sandbox/.github/issues/38
/hold
=> Codify the relationship between `knative-sandbox/.github` and `knative/.github`

workflow-templates/knative-boilerplate.properties.json, workflow-templates/knative-boilerplate.yaml
I wrote a [little tool](https://github.com/mattmoor/boilerplate-check) to facilitate checking file header boilerplate using some fairly simple fuzzy-matching heuristics.  This let's be drop yet another knobot check.
To see this in action, I ran this here with a number of boilerplate errors: https://github.com/knative/serving/pull/9486/files
I originally had this as part of `knative-style.yaml`, but pulled it out when I made it a matrix job, but I can fold it back together, just LMK folks preferences.
=> Create an action for validating knative boilerplate headers.

.github/workflows/sync.yaml
I suspect that we will need to move this to `knobots-actions` due to the limitations around actions triggering workflows we found elsewhere, but I wanted to at least fix this first.
=> Fix issue with action detecting '.git' from '.github'

workflow-templates/knative-style.yaml
for example logger.Warnf("Riding the storm at %v", time.Now()) is just
as good as logger.Warn("Riding the storm at ", time.Now()), but costs
much less at runtime.
/assign mattmoor
=> Suggest not to format the traling formatting arugment if it's the only one

workflow-templates/knative-style.yaml
This is currently missing stuff that are not part of the diff but still caused by the PR at hand. We've so far cleaned out all warnings anyway so everything should be assumed to be clean wrt. linting anyway.
=> Run golangci-lint on the entire codebase, not just new lines

workflow-templates/knative-style.yaml
e.g. always leave space for sprintf, but not for printf, which are different
/assign mattmoor
=> Make the script more precise and permit for more verbs and edge cases

workflow-templates/knative-security.properties.json, workflow-templates/knative-security.yaml
As per title. Also see https://github.blog/2020-09-30-code-scanning-is-now-available/. This is the action provided by Github mostly.
Tested here https://github.com/knative/serving/pull/9646.
I debated adding it to the `style` run but :man_shrugging:. Happy to move there if others think I should.
=> Run Github's security checks against our Golang code

workflow-templates/knative-security.yaml
We're seeing ["Missing analysis for base commit ad2ba89180a73b623cb9784d3e9d1f6f58fb5604"](https://github.com/knative-sandbox/eventing-kafka-broker/pull/268/checks?check_run_id=1224912335)  and that commit is the last commit on the main branch.
=> Security check on push on the main and release branches

workflow-templates/knative-style.yaml
Exclude wire generated files, `wire_gen.go`, from style checks.
=> Exclude wire gen files.

workflow-templates/knative-releasability.yaml
Example run with this change: https://github.com/n3wscott/discovery/runs/1353749988?check_suite_focus=true
=> update releasability script to match the out of date logic of knobots

.github/PULL_REQUEST_TEMPLATE.md
To better make PRs in all repos, use the PR template by default. All repos that do not define a PR template will use this inside knative-sandbox.
=> Add top level PR template

workflow-templates/knative-style.yaml
As per title. All repositories have been adjusted to oblige the respective rules, outstanding to merge are:
The respective PRs should merge soon though.
=> Update woke version to 0.4.1

workflow-templates/knative-boilerplate.yaml, workflow-templates/knative-donotsubmit.yaml, workflow-templates/knative-go-build.yaml, workflow-templates/knative-go-test.yaml, workflow-templates/knative-security.yaml, workflow-templates/knative-style.yaml, workflow-templates/knative-verify.yaml
Github has changed the default branch to `main` and we want to move all of our repos in the future too.
`sample-controller` sees no actions running on PRs currently due to this for example.
=> Add main branch as a target for all actions

workflow-templates/knative-style.yaml
Didn't garner a cult following, so let's just remove it.
/assign @mattmoor @markusthoemmes
=> Remove redundant format linter.

workflow-templates/knative-style.yaml
- 🎁  Switch from using `find` to `git ls-files`, which will only pick up files managed by `git`
- 🧹  Use Git attributes (from `.gitattributes`) to determine which files need linting, so repos can customize the linted files more easily.
/kind cleanup
=> Add support for git attributes, keep legacy filters for now

workflow-templates/knative-style.yaml
This patch fixes knative-style.yaml which currently missing single quote.
```release-note
NONE
```
/cc @evankanderson @n3wscott @mattmoor
=> Fix missing single quote in knative-style.yaml

workflow-templates/knative-style.yaml
To stay somewhat recent, I'm closely following development. All of our repos (modulo the PRs I just sent) are clean. The PRs I had to sent would be caught by the old version too though, so :shrug:.
=> Bump woke version to 0.5.0

workflow-templates/knative-releasability.yaml
Example run: https://github.com/knative-sandbox/eventing-rabbitmq/runs/1912935265?check_suite_focus=true
=> Fail releasability if NO-GO

.github/workflows/sync.yaml, workflow-templates/knative-releasability.yaml, workflow-templates/knative-release-notes.yaml
A few stray occurrences of `master` references we should now be able to drop safely.
=> Bend sync and release-note actions to run against main

workflow-templates/knative-style.yaml
Bumps golanglint-ci version to [v1.38](https://github.com/golangci/golangci-lint/releases/tag/v1.38.0) to pick up [importas linter](http://github.com/julz/importas) for https://github.com/knative/serving/pull/10885.
/assign @markusthoemmes
=> Bump golanglint-ci version

workflow-templates/knative-security.yaml
The scanner started barking like
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
So let's comply.
=> Remove explicit checkout from security action

workflow-templates/knative-release-notes.yaml
https://github.com/kubernetes/release uses
Go 1.16 only features like `os.MkdirTemp`
[1] https://golang.org/pkg/os/#MkdirTemp
=> Bump Go version to release notes workflow

workflow-templates/knative-go-build.yaml
The indent is wrong so it is failing in downstream.
Please refer to:
https://github.com/knative-sandbox/net-istio/actions/runs/834435863
https://github.com/knative-sandbox/net-kourier/actions/runs/834399431
This patch fix it.
/cc @benmoss @n3wscott @markusthoemmes
=> Fix indent for andstor/file-existence-action@v1

workflow-templates/knative-releasability.yaml
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
As per the release docs https://github.com/knative/release#update-the-knative-releasability-defaults.
/assign @evankanderson 
/assign @vaikas 
/assign @dprotaso
=> Bump releasability action to start asserting v0.24

workflow-templates/knative-go-test.yaml
This PR limits `merge` step to `pull_request` event only, otherwise when executed on push to `main` it fails due to missing `github.base_ref`.
- :bug: Fix merge step of unit test action
Fixes #127
=> Fix merge step of unit test action

workflow-templates/knative-releasability.yaml
- As per the release docs https://github.com/knative/release#update-the-knative-releasability-defaults.
=> Bump releasability action to start asserting v0.25

workflow-templates/knative-style.yaml
Newer is always better, right? Did a quick run through all repos with `woke` because the bump is quite big. No errors found.
/assign @julz
=> Bump the versions of our linting tools

workflow-templates/knative-boilerplate.yaml, workflow-templates/knative-donotsubmit.yaml, workflow-templates/knative-go-build.yaml, workflow-templates/knative-go-test.yaml, workflow-templates/knative-security.yaml, workflow-templates/knative-style.yaml, workflow-templates/knative-verify.yaml
We rename mkdocs to main branch in docs repo, this is not need it anymore
=> remove mkdocs branch from docs

workflow-templates/knative-go-test.yaml
Fix git identity in `Merge upstream` step.
For non-members of knative it seems these values are not set.
Fixes #137
=> Fix git identity in `Merge upstream` step

workflow-templates/knative-boilerplate.yaml, workflow-templates/knative-releasability.yaml, workflow-templates/knative-release-notes.yaml, workflow-templates/knative-style.yaml, workflow-templates/knative-verify.yaml
- :broom: Change `go get`s to `go install`
- :broom: Float the ko dependency
/kind cleanup
Fixes this warning we see everywhere:
```
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
=> Change 'go get' to 'go install'

workflow-templates/knative-verify.yaml
It causes binaries to get installed in the repo directory, which then messes up checkout.
In [this run](https://github.com/knative-sandbox/net-kourier/runs/4165607073?check_suite_focus=true#step:4:19) we see the checkout action trying to delete the net-kourier directory, which shouldn't exist yet. It exists because "install deps" was installing these binaries to `/home/runner/work/net-kourier/net-kourier` because that was the set as the `GOPATH` and `go install` says 
```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set. Executables in $GOROOT
are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.
```
@dprotaso @markusthoemmes
=> Remove GOPATH from knative-verify

workflow-templates/knative-style.yaml
- Always install tools in knative-style so that subsequent steps won't fail
/kind bug
Fixes #158
We don't need to fail fast, we can run all the linters, but since this step was missing the `if: always`, it would be skipped which means the other steps are definitely going to fail.
I tested this out here: https://github.com/benmoss/eventing-rabbitmq/runs/4562246793?check_suite_focus=true
=> Fix tools not being installed in knative-style

workflow-templates/knative-releasability.yaml
As per [the docs](https://github.com/knative/release#update-the-knative-releasability-defaults)
=> Bump releasability action to start asserting v1.2

.github/workflows/knative-security.yaml, workflow-templates/knative-security.yaml
[Release notes:](https://github.com/pierDipi/unicode-control-characters-action/releases/tag/v0.1.1)
- Log the position of the invalid character
/assign @dprotaso
=> Bump unicode action to v0.1.1

workflow-templates/knative-release-notes.yaml
You no longer need to figure out the start/end sha. The start-sha
defaults to the first common ancestor (merge-base) between the
target branch and prior branch.
The end-sha defaults to the HEAD of the requested branch.
=> Make the release notes task easier to run

workflow-templates/knative-style.yaml
woke reviewdog is giving a false negative on an picture/image file
Is blocking this PR https://github.com/knative/docs/pull/4747
```
Raw Output:
Error: ages/home-images/dkblue_event_intergrations_icon.svg:2842:40: [error] `GUYS` may be insensitive, use `folks`, `people`, `you all`, `y'all`, `yinz` instead
Error: [woke] reported by reviewdog 🐶
Error:  `gUyS` may be insensitive, use `folks`, `people`, `you all`, `y'all`, `yinz` instead
```
=> ignore .svg for woke

workflow-templates/knative-style.yaml
We have svg image files in the website repo, and need to ignore this files
cc @gabo1208
=> ignore newline EOF for svg

workflow-templates/knative-releasability.yaml
- Prepare for v1.3 Knative Release as per [release instructions](https://github.com/knative/release#14-days-prior-to-the-release)
=> Update knative-releasability.yaml for Knative 1.3 release

workflow-templates/knative-go-build.yaml, workflow-templates/knative-go-test.yaml, workflow-templates/knative-verify.yaml
/cc @dprotaso @chizhg  
Part of: https://github.com/knative/test-infra/issues/2985
- Reworking the simpler github actions to allow prow to mark it as required.
- The github treates each matrix permutation as a unique status so when we move to go 1.18 the status that we are tracking for 1.17 
will now be different. Current test status is `"Build (1.17.x, ubuntu-latest)"`
- Once this is merged, can a repo admin run add the new test briefly and run `gh api 
repos/knative/serving/branches/main/protection/required_status_checks/contexts`
=> Remove the matrix from some tests.

.github/release.yml
- :gift: Add global release notes template
The format is a merge between our common templates we use in release blog and k8s release-notes tool we used so far. 
With the template in place, release leads don't have to execute GH action to produce release notes in `.md` and copy it over. Rather press `Generate release notes` button in release edit view.
Future enhancement to consider, the process can be further automated with GH API calls, it's not 1 step process, but rather a chain. In a nutshell POST to generate notes with inputs -> content in response -> POST to edit/update release body. 
/cc @knative/knative-release-leads 
/cc @knative/technical-oversight-committee 
Fixes https://github.com/knative/community/issues/1499
Based on  docs: …
=> Add global release notes template
